### PR TITLE
Open new link in background tab. Display a context menu on long press.

### PR DESCRIPTION
**Pull request by alinux78**
screenshot_20151216-172741

### CODE REVIEW

**Comment by kuc** [comment]
:+1: 

Maybe you could also add menu entry suggested in #353 ?

**Comment by xunila** [comment]
yep. It's possible

**Comment by JonasCz** [comment]
Should not be more than a few lines of code to add a way to share the link.. 

It would also be super cool if there was a similar menu when long pressing on a bookmark or a history item for consistency.

**Comment by alinux78** [comment]
Context menu is also shown for images and history items. Did not have the time to handle bookmarks which are a bit more complex.

**Comment by Streetwalrus** [comment]
Additionally you should show the `title` text where relevant (typically shown in a mouseover popup in desktop browsers).

**Comment by JonasCz** [comment]
I don't think this is actually possible. I tried to do this in my own app a
while back (get the title of a link on long press) and it wasn't possible.

**Comment by Streetwalrus** [comment]
Ugh, indeed, I checked that out and all you get is the URL and the link text. Kinda sucks, Chromium does it and WebView is based on Chromium.

**Comment by ByteHamster** [comment]
@anthonycr would you merge this one please? :)

**Comment by eht16** [comment]
+1 It'd be cool if this could get merged. This is a great feature.

**Comment by anthonycr** [comment]
Thanks for the work on this, sorry I ignored this PR and letting merge conflicts happen. The good news is that the context menu is fully functional now with a lot of options. I just added the last bit of functionality that was missing, i.e. Share, in this commit https://github.com/anthonycr/Lightning-Browser/commit/b0d07298ddf4baad381e904b6f739f275b4a90f9 so I'm closing this now 👍

**Pull request closed without merging**
