### PR TITLE
code improvements

### PR DESCRIPTION
**Pull request by DF1E**
no new features are added or removed

### CODE REVIEW

**Comment by kuc** [comment]
I don't think that changing all tabs to spaces, or vice versa, in any open-source project is right thing to do (exception: mixed tabs/spaces in files of one type, etc.). It practically removes all code history - `git blame` on ANYTHING will now showing this one, super-huge commit.

**Comment by DF1E** [comment]
The main target was to improve the code and the reformat was a small addition. After moving to Android Studio the whole code was changed

**Comment by kuc** [comment]
Just [moving files don't break the diffs and `git blame`](https://github.com/anthonycr/Lightning-Browser/blame/dev/app/src/main/java/acr/browser/lightning/view/LightningView.java), but changing indentation is.

**Comment by DF1E** [comment]
Ok, I will close this pull request and push a new one only with the first commit

**Pull request closed without merging**
