### PR TITLE
NFC support

### PR DESCRIPTION
**Pull request by ByteHamster**
Please test before merging. I do not have access to a second device currently.

### CODE REVIEW

**Comment by anthonycr** [comment]
:+1: I will test it soon, thanks.

**Comment by ByteHamster** [comment]
Just had the opportunity to test this commit. It's not working, sorry.

**Comment by ArchieT** [comment]
But you haven't given up yet? That's a feature I would love to have — that's the only reason I use the stock AOSP browser, and not the Lightning Browser, on my Nexus S with pure CM11 (no gapps) — I use it when switching between my Nexus S and Nexus 5.

**Comment by ByteHamster** [comment]
I don't have time for programming currently... Let's wait for the semester break ;)

**Pull request closed without merging**
