### PR TITLE
Update I2P to version 0.9.41

### PR DESCRIPTION
**Pull request by schleif**
Play Store does not support apps which have a 32bit version only. Therefore Lightning's dependency on I2P needs an update to 0.9.41. This version ships a 64 bit version of libjbigi which is the dependency on I2P's site that contains native calls.

You might wait for the update of the maven dependency. I needed this for a release on Google Play. I added support of U2F to Lightning. Sadly, I cannot merge it. I must be GPLv3 compliant :'(
Check out this: https://github.com/cotechde/U2F-Browser

### CODE REVIEW

**Comment by anthonycr** [comment]
Thanks for posting a fix. I was wondering where the I2P maven release of 0.9.41 is. I'm going to pull in the submodules for the `:helper` and `:client` modules until they released to maven so that release can proceed.

Maybe I'll ping I2P folks to see where the dependencies are at.

**Comment by anthonycr** [comment]
Just an FYI, I found I needed to exclude `x86` architecture from the build as uploading to google play complained that I didn't also support `x86_64`. Not sure if you experienced the same problem or not, but I added the following block to the gradle build files to fix it.
```
ndk {
     abiFilters "arm64-v8a", "armeabi-v7a", "armeabi", "mips"
}
```

**Comment by anthonycr** [comment]
I also pinged the I2P twitter account about it and they said they'd get around to pushing the update to maven: https://twitter.com/i2p/status/1168237907309674496

**Comment by schleif** [comment]
> Just an FYI, I found I needed to exclude `x86` architecture from the build as uploading to google play complained that I didn't also support `x86_64`. Not sure if you experienced the same problem or not, but I added the following block to the gradle build files to fix it.
> 
> ```
> ndk {
>      abiFilters "arm64-v8a", "armeabi-v7a", "armeabi", "mips"
> }
> ```

Oh yeah, this issue appeared the time I tried to update it. Looks that I passed the moment Google adapts the infrastructure exactly.

**Comment by anthonycr** [comment]
I2P Folks have published the latest artifact to maven, 0.9.42 https://mvnrepository.com/artifact/net.i2p.android/client/0.9.42

I think it's safe to close this now.

**Pull request closed without merging**
