### PR TITLE
Complete S.Chinese.

### PR DESCRIPTION
**Pull request by ageback**

### CODE REVIEW

**Comment by kuc** [comment]
I think that commit 00c92af is here accidentally...

**Comment by anthonycr** [comment]
@ageback any way you can revert the exit change before I merge? If not I can always just revert myself after merge.

**Comment by ageback** [comment]
@anthonycr I am glad to revert it but I don't know how.

**Comment by kuc** [comment]
@ageback 
```
git checkout master
git branch master-copy
git reset --hard 025714b
git push --force
```

**Comment by ageback** [comment]
@kuc I see. Thanks. Now it's OK to merge.

**Comment by anthonycr** [comment]
Thanks!

**Pull request merged**
