### PR TITLE
Issue #362:  Show file size at Download dialog box

### PR DESCRIPTION
**Pull request by alinux78**
screenshot_20160105-183351

### CODE REVIEW

**Comment by kuc** [comment]
:+1:

**Comment by relan** [comment]
That's a cool addition!

I'd like to suggest a slight improvement to the text:

> Do you want to download 2.02 MB?

would be better because this is the way people speak. Google recommends to write user-visible messages in this way.

**Comment by M2ck** [comment]
Agree with relan, it's odd to see text after an interrogation mark.

**Comment by alinux78** [comment]
Created a new request #390  because the branch was messed-up

**Pull request closed without merging**
