### PR TITLE
Add clear_cookies string to fix context inconsistencies

### PR DESCRIPTION
**Pull request by pejakm**

### CODE REVIEW

**Comment by anthonycr** [comment]
I guess I'm not really understanding the reason for this change? I know that the name of the string resource is different, but (at least in english) the string makes sense as both an action and the title of the dialog. Does it not make sense in other languages (e.g. serbian)  to have the action "Clear history" be the same as the title of the dialog? 

btw, sorry I am just now replying to this, been busy for a few days and haven't looked at PRs in a while.

**Comment by pejakm** [comment]
> Does it not make sense in other languages (e.g. serbian) to have the action "Clear history" be the same as the title of the dialog?

Exactly. Since there were two different strings for action and title for cookies and cache, I've put the title in infinitive and action in imperative (the usual way we do translation for Serbian). And since there are different string for cookies and cache, there should be also the same for history.

P. S. I now see that I named commit wrong, it should have been `Add clear_history string to fix context inconsistencies`. :)

**Comment by pejakm** [comment]
To clarify further, privacy setting in Serbian now look like this:

Action | Dialog title
------------- | -------------
Clear cache | x
Cleaning history | Cleaning history
Clear cookies | Cleaning cookies
Clear web storage | x

**Comment by anthonycr** [comment]
Okay great, sorry for delayed reply. Also, localization is complicated :)

**Comment by pejakm** [comment]
Unfortunately, I don't now how to do that. :D I'll just create another pull request.

**Comment by pejakm** [comment]
Looks like I've make it. Please let me know if there are any more issues with this PR.

**Comment by anthonycr** [comment]
:D great, looks good! merging.

**Pull request merged**
