### PR TITLE
material design for erveryone..

### PR DESCRIPTION
**Pull request by DF1E**
use appcompat on all API's because of its backward compatibility

### CODE REVIEW

**Comment by anthonycr** [comment]
Looks good from a cursory glance, and also is a good idea, I'll review it some more later today just to be safe. Just FYI, I might add back the styles-v21 xml file you deleted because I don't want any of the holo-blue resources showing up on older devices (I've noticed the support library resources don't quite do away with it all). Apart from that though :+1:

**Comment by DF1E** [comment]
Thanks for feedback! Try to get resources only with "?" instead of "?attr". Then you will get recources from appcompat-library..

**Comment by anthonycr** [comment]
Ah, thanks, I was mistaken on the use of the ? vs ?attr.

**Comment by anthonycr** [comment]
Hmmm, so this causes a bunch of issues with the styling for pre-Lollipop devices (the removal of the api specific styles) as well as breaking the background color functionality of the toolbar (due to modifications to activity_main and toolbar layout files). 

I'll just merge it anyway and fix the problems. Thanks!!! :+1:

**Pull request merged**
