### PR TITLE
Translated from scratch

### PR DESCRIPTION
**Pull request by MarkThat**
Some errors should be fixed now, please include it in both lite and plus versions asap =). It contains major translation updates and some things i missed before.

### CODE REVIEW

**Comment by MarkThat** [comment]
Shall i push also the one for master branch?

**Comment by kuc** [comment]
>Shall i push also the one for master branch?

Definitely no - @anthonycr periodically merges changes from `dev` to `master`.
But you must resolve merge conflict manually first.

**Comment by MarkThat** [comment]
Well where do i see the errors?

**Comment by kuc** [comment]
Open console/Git Bash on your local repo folder and type:
```
git remote add upstream https://github.com/anthonycr/Lightning-Browser.git
git fetch upstream
```
and then `git merge upstream/dev`, or use visual merge tool in IDE/some GUI for git.

**Comment by MarkThat** [comment]
I forgot to add that i'm doing it from browser.

**Comment by kuc** [comment]
>I forgot to add that i'm doing it from browser.

Uhh, so maybe try other approach...

1) Copy [your changed file](https://raw.githubusercontent.com/MarkThat/Lightning-Browser/70f7fbd1238ef6800306f02e38fea17432ee07aa/app/src/main/res/values-it/strings.xml) somewhere
2) Delete your fork in repo settings
3) Create a fresh fork and edit file again. Be cautious seeing what changed in original file, when you are pasting your copied changes back, so you can update your changes adequately

**Comment by MarkThat** [comment]
Aight thanks, i'm gonna close this now.

**Pull request closed without merging**
