### PR TITLE
Remove unnecessary files

### PR DESCRIPTION
**Pull request by AltNico**
Basically, all I have done was adding some missing files/directories to .gitignore and the executing the following commands:
git rm --cached -r ./
git add --all

### CODE REVIEW

**Comment by kuc** [comment]
Maybe `*.iml` files shouldn't be deleted, importing project to Android Studio will be easier with them (just "open existing project" instead of "import sources from gradle project").

**Comment by AltNico** [comment]
@kuc I know that importing the project is easier with `*.iml` files but they were in the `.gitignore` file before, see [here](https://github.com/anthonycr/Lightning-Browser/blob/master/.gitignore#L27).
Should I remove the entry from the `.gitignore` file?

**Comment by kuc** [comment]
@anthonycr

**Comment by anthonycr** [comment]
Sorry I'm late to respond to this, college finals suck... Anyway, if the iml files make importing the project easier, maybe we should leave them in and just get rid of the line in the gitignore. For me personally, it's not going to be a problem either way as I know the quirks of the repo, but from someone elses perspective, it might be annoying if the iml files contain some little thing.

I think the iml files muck up the repo, but maybe they are indeed useful. Also, I remember reading something about it being important to leave the gradle wrapper jar in the repo for easier importing, did I remember that wrong?

**Comment by AltNico** [comment]
@anthonycr @kuc I pushed a new commit where I readded `.iml` and gradle wrapper files.
`.iml` files make it easier to import the project and the gradle wrapper lets you build the project without gradle installed.

**Comment by anthonycr** [comment]
Looks great, thanks @AltNico

**Pull request merged**
