### PR TITLE
Updated history and bookmarks page

### PR DESCRIPTION
**Pull request by ByteHamster**
Removed shadow and added borders ("CardsUI"). Increased padding and decreased margin.

 old: 

 old:

### CODE REVIEW

**Comment by kuc** [comment]
:+1:

**Comment by HendrikBoone** [comment]
On homepage it looks not bad, but history view gives you now a row less. I would like a simple list with line separation more, as it allows more content and is gives you less distraction.

**Comment by ByteHamster** [comment]
Switched to a simple list. @anthonycr Can this be merged?

**Comment by anthonycr** [comment]
Added these changes in this commit https://github.com/anthonycr/Lightning-Browser/commit/ef86b7d54ddab5406801ef014b4d131eaa73e0b9 since there's a merge conflict. Closing this since the changes are now in, thanks.

**Pull request closed without merging**
