### PR TITLE
Adding support for WebRTC

### PR DESCRIPTION
**Pull request by anthonycr**
# Summary

This PR provides support for WebRTC, by adding the necessary UI to request permissions from the user. The resources requested by the site are mapped to the needed permissions and requested if necessary. Each time a site requests to use a resource, a request dialog will show.

As this is can cause potential problems, and support for WebRTC has been a controversial topic in the past, I am opening this feature up for comments and suggestions before committing it directly.

Problems I see currently:
- Added three permissions which will be automatically granted to the browser on API < 21 (upside is that the permissions are not used except when expressly granted through request dialog).

# Screenshots

### CODE REVIEW

**Comment by rancidfrog** [comment]
Having a way to enable/disable it in general would also be useful.

Also, a shortcut maybe in context menu that links to it something like the following:
A link appearing here,

Which takes you to switches,

**Comment by anthonycr** [comment]
@rancidfrog a toggle is a good idea, so if it's off it will just ignore all requests. Maybe default to off since I don't think too many people are using WebRTC in their every day web browsing?

**Comment by rancidfrog** [comment]
That is what I would suggest.
But, these days you would be surprised; and, you might end up with a lot of people opening issues about how something broke all of a sudden.

My suggestion would be, 
Since you are able to detect webRTC usage, from screenshots with permission requests:

- Have a `flag`, i.e. webRTC_First_Usage
- On first usage display dialog asking user whether to enable/disable webRTC
- `flag` triggered, dialog should not be displayed anymore | **AND** if user select `Enable` display permission request, if not block requests, and disable future use

**Comment by anthonycr** [comment]
An option, off by default, has been added to settings for "WebRTC Support." Turning it on will allow a website to request for additional permissions, you can still deny access to the website. Every permissions request will trigger a permissions dialog right now, preference for a site is not remembered just yet.

**Comment by anthonycr** [comment]
Just updated so that resource grant is remembered for the entirety of the browsing session.

**Comment by rancidfrog** [comment]
anthonycr Have you tested against leaks? Because built from master and still got IP leaks: #285

**Pull request merged**
